openapi: 3.1.0
info:
  title: Finance Buddy API
  version: 1.0.0
servers:
  - url: https://api.finance-buddy.example.com
paths:
  /api/gmail/connect:
    get:
      summary: Start Gmail OAuth (PKCE)
      responses: { '302': { description: Redirect } }
  /api/gmail/callback:
    get:
      summary: Gmail OAuth callback
      responses: { '302': { description: Redirect } }
  /api/gmail/connections:
    get:
      summary: List Gmail connections
      responses: { '200': { description: OK } }
  /api/gmail/disconnect:
    post:
      summary: Revoke token and hard-delete the connection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [connection_id]
              properties:
                connection_id: { type: string, format: uuid }
                revoke: { type: boolean, default: true }
      responses: { '204': { description: No Content } }
  /api/gmail/manual-sync:
    post:
      summary: Manual sync (date range + senders + paging; oldest→newest)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [connection_id, date_from, date_to]
              properties:
                connection_id: { type: string, format: uuid }
                date_from: { type: string, format: date }
                date_to: { type: string, format: date }
                senders:
                  type: array
                  items: { type: string }
                page: { type: integer, default: 1, minimum: 1 }
                pageSize: { type: integer, default: 50, maximum: 100 }
                sort: { type: string, enum: [asc, desc], default: asc }
      responses:
        '200': { description: OK }
  /api/gmail/backfill:
    post:
      summary: Orchestrate manual sync across chunks (resumable)
      responses: { '202': { description: Accepted } }
  /api/emails/search:
    post:
      summary: Search stored emails
      responses: { '200': { description: OK } }
  /api/transactions/search:
    post:
      summary: Search extracted transactions
      responses: { '200': { description: OK } }